-- =============================================================================
-- Recipe App — seed data
--
-- The item catalog (ingredients) is now PER-FAMILY: each row requires a
-- family_id, and families are created at runtime when users sign up. There is
-- therefore no global seed to load here — each family curates its own catalog
-- in the app (Family tab → Item catalog).
--
-- (Intentionally empty. Kept as a placeholder in the apply order.)
-- =============================================================================
